import Head from 'next/head'
import Link from 'next/link'

export default function Home({pages}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon" />
      </Head>
      <header>
        <div className="container">
          <div className="menu">
            {pages.map((page, index) => (<Link key={index} href={page.pageUrl}>{page.localizeInfos.en_US.title}</Link>))}
          </div>
        </div>
      </header>
    </>
  );
}

export async function getServerSideProps({req, res}) {
  const response = await fetch(
    "https://realestate.oneentry.cloud/api/content/pages",
    {
      method: "get",
      headers: {
        'x-app-token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicmVhbGVzdGF0ZSIsInNlcmlhbE51bWJlciI6OSwiaWF0IjoxNzA5MzY3MjQ0LCJleHAiOjE3NDA5MDMxOTV9.Nmzub48Kf11VSBlNCL1yi5g_OH4IAtRr5uQhZMuchMQ'
      },
    }
  );
  const pages = await response.json();
  return {
    props: {
      pages,
    }
  }
}